"use strict";

// api urls
export const PROD_V2 = "https://api.kod.mobi/v2";
export const PROD_V2_1 = "https://api.kod.mobi/v2.1";

// cookie
export const COOKIE_SESSION_ID = "km-id";
export const COOKIE_DESTINATION = "km-dest";

// events
export const EVENT_READY = "ready";
export const EVENT_SESSION_CREATED = "session:created";
export const EVENT_SESSION_LOADED = "session:loaded";
export const EVENT_SESSION_EXPIRED = "session:expired";
export const EVENT_SESSION_SUCCESS = "session:success";
export const EVENT_SESSION_TIMER = "session:timer";
export const EVENT_CHANNEL_TIMER = "channel:timer";
export const EVENT_ERROR = "error";

// sys messages
export const PROJECT_HAS_NO_CHANNELS = "ERROR_PROJECT_HAS_NO_CHANNELS";
export const PROJECT_HAS_NO_CHANNEL = "ERROR_PROJECT_HAS_NO_CHANNEL";
export const USER_NOT_AUTHORIZE_ON_CHANNEL =
	"ERROR_USER_NOT_AUTHORIZE_ON_CHANNEL";
export const SESSION_EXPIRED = "ERROR_SESSION_EXPIRED";
export const MESSAGE_WRONG_CODE = "ERROR_MESSAGE_WRONG_CODE";
export const CHANNEL_NOT_ALLOWED_COUNTRY = "ERROR_CHANNEL_NOT_ALLOWED_COUNTRY";
export const MESSAGE_ATTEMPT = "ERROR_MESSAGE_ATTEMPT";
export const PHONE_BLOCKED = "ERROR_PHONE_BLOCKED";
export const USER_BLOCKED = "ERROR_BLOCKED";
export const CHALLENGE_FAILED = "ERROR_CHALLENGE";
export const BAD_REQUEST = "ERROR_BAD_REQUEST";
export const WRONG_BALANCE = "ERROR_WRONG_BALANCE";
export const ACCESS_DENIED = "ERROR_ACCESS_DENIED";

export default {
	URL: {
		V2: PROD_V2,
		V2_1: PROD_V2_1,
	},
	EVENT: {
		SESSION_CREATED: EVENT_SESSION_CREATED,
		SESSION_LOADED: EVENT_SESSION_LOADED,
		SESSION_EXPIRED: EVENT_SESSION_EXPIRED,
		SESSION_SUCCESS: EVENT_SESSION_SUCCESS,
		SESSION_TIMER: EVENT_SESSION_TIMER,
		CHANNEL_TIMER: EVENT_CHANNEL_TIMER,
		ERROR: EVENT_ERROR,
	},
	ERROR: {
		PROJECT_HAS_NO_CHANNELS,
		PROJECT_HAS_NO_CHANNEL,
		USER_NOT_AUTHORIZE_ON_CHANNEL,
		SESSION_EXPIRED,
		MESSAGE_WRONG_CODE,
		CHANNEL_NOT_ALLOWED_COUNTRY,
		MESSAGE_ATTEMPT,
		PHONE_BLOCKED,
		USER_BLOCKED,
		CHALLENGE_FAILED,
		BAD_REQUEST,
		WRONG_BALANCE,
		ACCESS_DENIED,
	},
};
